## Intro

In [68]:
# NumPy => Numerical Python

import numpy as np

revenus = [1800,1500,2200,3000,2171]
print(type(revenus))

# Moyenne
np.mean(revenus)

<class 'list'>


2134.2

## Array

Création d'un array :

In [55]:
revenus_array = np.array(revenus)
revenus_array

array([1800, 1500, 2200, 3000, 2171])

In [15]:
n = 5
# Array rempli de 0 pour n éléments
np_zeros = np.zeros(n)
print(np_zeros)
# Array rempli de 1 pour n éléments
np_ones = np.ones(n)
print(np_ones)
# Array rempli de façon linéaire d'un chiffre de départ jusqu'à un chiffre de fin en fonction du pas souhaité
np_arange = np.arange(0,5,1)
print(np_arange)
np_arange = np.arange(10,20,3)
print(np_arange)
# Array rempli de n valeurs espacées uniformement entre un interval donné
# Exemple : Ici on souhaite un array de 4 élements, où la valeur de départ est 0 et la valeur de fin soit 10
np_linspace = np.linspace(0,10,4)
print(np_linspace)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]
[10 13 16 19]
[ 0.          3.33333333  6.66666667 10.        ]


<div class="alert alert-warning" >Un array ne peut être que d'un seul type.</div>

In [18]:
# Afficher le type d'un array
print(np_arange.dtype)
print(np_linspace.dtype)

int64
float64


In [21]:
# Accès à un élément
print(revenus_array[2])
# Accès au dernier élément
print(revenus_array[-1])

2200
2171


In [56]:
# Modifier une valeur
print(revenus_array)
revenus_array[2] = 3500
print(revenus_array)

[1800 1500 2200 3000 2171]
[1800 1500 3500 3000 2171]


In [30]:
# Accès une plage d'éléments
revenus_array[1:4]

array([1500, 3500, 3000])

In [31]:
# Trois premiers
revenus_array[:3]

array([1800, 1500, 3500])

In [32]:
# A partir du troisième jusque la fin
revenus_array[2:]

array([3500, 3000, 2171])

In [34]:
# Si le "pas" est négatif on peut inverser le tableau
revenus_array[::-1]

array([2171, 3000, 3500, 1500, 1800])

In [46]:
# Lister en fonction d'un "pas"
items = np.arange(0,20)
print(items)
# Lister un element sur deux
print(items[::2])
# Lister tous les élements à partir de l'indice 10 mais avec un pas de 3
print(items[10::3])
# Lister les éléments à partir de l'indice 6 jusqu'à 16 mais avec un pas de 4
print(items[6:16:4])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[10 13 16 19]
[ 6 10 14]


In [48]:
# Lister en fonction d'une condition
# On liste tous les élements du tableau dont la valeur est strictement supérieure à 2000
revenus_array[ revenus_array > 2000 ]

array([3500, 3000, 2171])

In [50]:
# Lister avec plusieurs conditions
# On liste tous les éléments de lu tableau dont la valeur est comprise strictement entre 2000 et 3000
revenus_array[ (revenus_array > 2000) & (revenus_array < 3000) ]

array([2171])

In [53]:
# On liste tous les éléments de du tableau dont la valeur est comprise strictement supérieure à 2000 OU strictement inférieure à 3000
# cad TOUT, ici c'est juste pour l'exemple de syntaxe avec le pipe (|) élément logique du "OU"
revenus_array[ (revenus_array > 2000) | (revenus_array < 3000) ]

array([1800, 1500, 3500, 3000, 2171])

In [57]:
# On peut modifier plusieurs élément d'un array avec une condition
revenus_array[ revenus_array < 2500 ] = 0
print(revenus_array)

[   0    0 3500 3000    0]


In [58]:
# Accès aux dimensions d'un array
revenus_array.shape

(5,)

In [67]:
# Autres fonctions
revenus_array = np.array(revenus)
print(revenus_array)
# moyenne
print(revenus_array.mean())
# Retourner la valeur max présente dans notre tableau
print(revenus_array.max())
# Retourner la valeur minimale présente dans notre tableau
print(revenus_array.min())
# Retourner l'index de la valeur minimale présente dans notre tableau
print(revenus_array.argmin())
# Retourner l'index de la valeur maximale présente dans notre tableau
print(revenus_array.argmax())
# Trier le tableau par ordre croissant
revenus_array.sort()
print(revenus_array)
# Calculer la somme de toutes les valeurs du tableau
print(revenus_array.sum())

[1800 1500 2200 3000 2171]
2134.2
3000
1500
1
3
[1500 1800 2171 2200 3000]
10671


In [72]:
# Array multidimension
array1 = np.array([
    [1,2],
    [3,4],
    [5,6]
])
array2 = np.array([
    [1,2,3],
    [4,5,6],
])
print(array1, array1.shape) # 3 éléments de 2 col
print(array2, array2.shape) # 2 éléments de 3 col

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 3]
 [4 5 6]] (2, 3)


In [85]:
# Matrice

A = np.array([ [2,-2], [5,3] ])
B = np.array([ [-1,4], [7,-6] ])

# Somme de deux matrices
print("Somme de A+B :")
print(A+B)
# Multiplcation de deux matrices
print("Produit de A*B")
print(A*B)
# A ne pas confondre avec un produit matricielle
print("Produit matricielle de [A.B]")
print(np.dot(A,B))

C = np.array([ [2,4,6], [8,10,12] ])


Somme de A+B :
[[ 1  2]
 [12 -3]]
Produit de A*B
[[ -2  -8]
 [ 35 -18]]
Produit matricielle de [A.B]
[[-16  20]
 [ 16   2]]


In [86]:
# Accès aux datas
hugo = [1300, 400, 23] # salaire | cout | age
richard = [1700, 560, 24]
emilie = [2500, 900, 30]
gaspard = [3000, 1000, 22]
jean = [2400, 700, 35]

clients = [hugo, richard, emilie, gaspard, jean]

print(clients)

[[1300, 400, 23], [1700, 560, 24], [2500, 900, 30], [3000, 1000, 22], [2400, 700, 35]]


In [88]:
data = np.array(clients)
print(data)

[[1300  400   23]
 [1700  560   24]
 [2500  900   30]
 [3000 1000   22]
 [2400  700   35]]


In [90]:
# Accès au salaire du client Hugo (première ligne, premiere colonne)
print(data[0,0])

1300


In [91]:
# Accès aux informations du client Hugo (toute la ligne)
print(data[0, :])

[1300  400   23]


In [93]:
# Accès aux âges de tous les clients (toutes les ligne, de la troisième colonne)
print(data[:, 2])

[23 24 30 22 35]


In [94]:
# Accès aux clients de plus ou égale à de 30 ans
print(data[ data[:, 2] >= 30 ])

[[2500  900   30]
 [2400  700   35]]


In [95]:
# Accès aux clients avec un salaire de moins de 2000
print(data[ data[:, 0] < 2000 ])

[[1300  400   23]
 [1700  560   24]]


In [99]:
fred = [4500, 840, 17]

# Ajouter un nouvel élément au tableau numpy
data = np.vstack((data, fred))
print(data)

[[1300  400   23]
 [1700  560   24]
 [2500  900   30]
 [3000 1000   22]
 [2400  700   35]
 [4500  840   17]
 [4500  840   17]]
